services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    networks:
      - cloudflared

networks:
  cloudflared:
    driver: overlay