---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cputemp: true
    uptime: true
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank