version: "3.8"

services:
  portfolio:
    image: pldubouilh/gossa
    mem_limit: 50m
    memswap_limit: 100m
    ports:
      - "3500:3500"
    volumes:
      - ./portfolio/data:/shared:ro
    command: ./gossa -ro -p 3500
    restart: always
    networks:
      lan:
         ipv4_address: 10.5.0.5

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    mem_limit: 50m
    memswap_limit: 100m
    restart: always
    ports:
      - 4000:3000
    volumes:
      - ./links/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      lan:
         ipv4_address: 10.5.0.9

  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: always
    volumes:
      - ./memos/:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      lan:
         ipv4_address: 10.5.0.10

networks:
  lan:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
