apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotify-pv
  namespace: gotify
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/gotify_data/
    type: DirectoryOrCreate