- Personal:
    - Portfolio:
        icon: si-raspberrypi
        href: https://jonathan.com.ar
        ping: jonathan.com.ar
    - Logs:
        icon: si-grafana
        href: https://logs.jonathan.com.ar
        ping: logs.jonathan.com.ar
    - Pihole:
        icon: si-pihole
        href: https://dns.jonathan.com.ar
        ping: dns.jonathan.com.ar
    - Portainer:
        icon: si-portainer
        href: https://portainer.jonathan.com.ar
        ping: portainer.jonathan.com.ar

- Apps:
    - Waifuland:
        icon: si-myanimelist
        href: https://waifuland.jonathan.com.ar/api
        ping: waifuland.jonathan.com.ar
    - Infobae:
        icon: si-newyorktimes
        href: https://noticias.jonathan.com.ar/api/infobae
        ping: noticias.jonathan.com.ar

- External:

    - Blog:
        icon: si-hashnode
        href: https://blog.jonathan.com.ar
        ping: blog.jonathan.com.ar
    - Pentest:
        icon: si-hackaday
        href: https://pentest.jonathan.com.ar
        ping: pentest.jonathan.com.ar