---
- name: Create folders
  hosts: node01
  tasks:
    - name: create multiple folders
      file:
        path: "$HOME/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - logs
        - scripts
        - www
        - security
        - backup
