version: '3.9'

networks:
  web:
    external: true

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel-homelab
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - web

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/Buenos_Aires'
      WEBPASSWORD: ''
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  portfolio:
    container_name: portfolio-homelab
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data # Add files here to be served
    ports:
      - 3500:3500
    networks:
      - web

  arcade:
    container_name: arcade-homelab
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./page:/app/page # the actual application
    ports:
      - 3000:3000
    networks:
      - web

  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    volumes:
      - ~/.thelounge:/var/opt/thelounge
    restart: unless-stopped

  gossa:
    image: pldubouilh/gossa
    ports:
      - "8001:8001"
    volumes:
      - ./data:/shared
    networks:
     network:
       ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
