version: '3.9'

networks:
  web:
    external: true

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel-homelab
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - web

  portfolio:
    container_name: portfolio-homelab
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - 3500:3500
    networks:
      - web
