services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    user: 61000:61000
    security_opt:
      - no_new_privileges:true
      - seccomp:unconfined
    privileged: true
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      INFO: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"