services:
  
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: dns.jonathan.com.ar
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  pihole:
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: dns.jonathan.com.ar
      VIRTUAL_PORT: 80
    extra_hosts:
      - 'jonathan.com.ar:192.168.0.242'
    restart: always
