services:
  nc:
    image: nextcloud:apache
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_USER=
    ports:
      - 8080:80
    volumes:
      - nc_data:/var/www/html

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_USER=
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: always
    privileged: true
    environment:
      CONTAINERS: 1
      INFO: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"

  dashdot:
    image: mauricenino/dashdot
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: "true"
