services:

  waifuland_dev:
    image: dyallo/waifuland-api
    env_file:
      - waifuland.dev.env
    ports:
      - 4100:4000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - waifuland_dev

  waifuland_prod:
    image: dyallo/waifuland-api
    ports:
      - 4200:4000
    env_file:
      - waifuland.prod.env
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    networks:
      - waifuland_prod

networks:
  waifuland_dev:
    driver: overlay
  waifuland_prod:
    driver: overlay