# https://dev.to/nownabe/secure-user-in-docker-1b5m
# https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
# https://forums.docker.com/t/docker-swarm-limit-ressources/113959/3
# https://stackoverflow.com/questions/45282608/how-to-directly-mount-nfs-share-volume-in-container-using-docker-compose-v3
# https://dozzle.dev/guide/swarm-mode

services:

  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    networks:
      - dozzle
    deploy:
      mode: global

networks:
  dozzle:
    driver: overlay