services:
  dashdot:
    image: mauricenino/dashdot
    user: 1000:1000
    security_opt:
      - seccomp:~/security/default.json
      - no-new-privileges:true
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: "true"

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    privileged: true
    restart: always
    environment:
      CONTAINERS: 1
      INFO: 1
      TASKS: 1
      POSTS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"

