---
- name: Configure and schedule tasks
  hosts: raspberry
  become: yes

  tasks:
    - name: Remove unused packages
      cron:
        name: "Autoremove and clean"
        minute: 0
        hour: 3
        weekday: 1
        job: "apt-get autoremove -y && apt-get clean"
        user: dyallo

    - name: Run usage script every hour
      cron:
        name: "Run usage script"
        minute: "0"
        job: "sh $HOME/scripts/usage.sh >> $HOME/logs/usage.log"
        user: dyallo

    - name: Run alerts script every hour
      cron:
        name: "Run alerts script"
        minute: "0"
        job: "sh $HOME/scripts/alerts.sh >> $HOME/logs/alert.log"
        user: dyallo

    - name: Run backup script every Monday at 3 AM
      cron:
        name: "Run backup script"
        minute: "0"
        hour: "3"
        weekday: "1"
        job: "sh $HOME/scripts/backup.sh $HOME/www/* >> $HOME/logs/backup.log"
        user: dyallo
