---
- name: create files and folders
  hosts: raspberry
  gather_facts: false
  tasks:
    - name: create multiple folders
      file:
        path: "$HOME/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - logs
        - scripts
        - www

    - name: copy scripts
      copy:
        src: "../scripts/{{ item }}"
        dest: "$HOME/scripts/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - alerts.sh
        - backup.sh
        - usage.sh

    - name: copy compose files
      copy:
        src: "../docker/{{ item }}"
        dest: "$HOME/www/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - pihole.compose.yml
        - portfolio.compose.yml
        - shared.compose.yml
        - status.compose.yml
        - homepage.compose.yml
        - logs.compose.yml

    - name: copy folders
      copy:
        src: "../docker/{{ item }}"
        dest: "$HOME/www/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
        directory_mode: 0755
      with_items:
        - links
        - portfolio
        - shared