---
- name: create files and folders
  hosts: raspberry
  become_user: dyallo
  gather_facts: false
  
  tasks:
    - name: create multiple folders
      file:
        path: "$HOME/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - logs
        - scripts
        - www

    - name: copy scripts
      copy:
        src: "../files/scripts"
        dest: "$HOME/scripts"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: copy docker
      copy:
        src: "../files/docker"
        dest: "$HOME/www/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755