---
- name: install sqlite3
  hosts: raspberry
  become: yes

  tasks:
    - name: Run apt-get update
      become: yes
      apt: update_cache=yes

    - name: Install sqlite3
      become: yes
      apt: name=sqlite3 state=present

    - name: Copy SQL files
      become: yes
      copy:
        src: "../database/{{ item }}"
        dest: "$HOME/db/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      with_items:
        - create.sql
        - sample.sql

    - name: Create database file
      become: yes
      shell: touch "$HOME/db/logs.db"

    - name: Create database schema
      become: yes
      shell: sqlite3 "$HOME/db/logs.db" < "$HOME/db/create.sql"

    - name: Insert sample data
      become: yes
      shell: sqlite3 "$HOME/db/logs.db" < "$HOME/db/sample.sql"