---
- name: install turso
  hosts: node02
  become: yes

  tasks:
    - name: Run apt-get update
      become: yes
      apt: update_cache=yes
    
    - name: Install curl
      become: yes
      apt: name=curl state=present

    - name: Run curl command
      become: yes
      shell: curl -sSfL https://get.tur.so/install.sh | bash

    - name: Source bashrc
      become: yes
      shell: . /home/{{ ansible_user }}/.bashrc

    - name: Auth to Turso
      become: yes
      shell: turso auth login --headless
      register: turso_auth

    - name: Print auth url
      debug:
        msg: "{{ turso_auth.stdout }}"

    - name: Ask for token
      pause:
        prompt: "Enter the token from the URL above"
      register: prompt_answer

    - name: Set Fact
      set_fact:
        turso_token: "{{ prompt_answer }}"

    - name: Set token
      become: yes
      shell: turso config set token "{{ turso_token }}"

    