---
- name: check docker version
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Run docker version and save output
      become: yes
      shell: docker version
      register: docker_version

    - name: Print docker version
      debug:
        msg: "{{ docker_version.stdout }}"