version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    mem_limit: 50m
    memswap_limit: 100m
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - ./links/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      lan:
         ipv4_address: 10.5.0.9

  dashdot:
    image: mauricenino/dashdot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    networks:
      lan:
         ipv4_address: 10.5.0.11

  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    volumes:
      - ./memos/:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      lan:
         ipv4_address: 10.5.0.10

  ## https://dozzle.dev/guide/remote-hosts#connecting-with-a-socket-proxy
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    privileged: true
    environment:
      CONTAINERS: 1
      INFO: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"

networks:
  lan:
   ipam:
    config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1