services:
  server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      ONLINE_MODE: false
      INIT_MEMORY: 2G
      MAX_MEMORY: 5G
    volumes:
     - ./server:/data