version: '3.8'

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    mem_limit: 50m
    memswap_limit: 100m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080