version: '3.9' 
 
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    mem_limit: 50m
    memswap_limit: 100m
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Buenos_Aires'
      WEBPASSWORD: ${WEBPASSWORD}
    env_file:
      - .env
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped