version: '3.8'

services:
  gossa:
    image: pldubouilh/gossa
    mem_limit: 50m
    memswap_limit: 100m
    ports:
      - "8001:8001"
    volumes:
      - ./shared/data:/shared
    networks:
     network:
       ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1