apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-pvc
  namespace: gotify
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: gotify-pv