apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
  namespace: homepage
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/homepage_data/
    type: DirectoryOrCreate