apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP