## https://github.com/marketplace/actions/setup-grafana-k6
## https://github.com/marketplace/actions/run-grafana-k6-tests

name: K6 Performance Test

on:
  workflow_run:
    workflows: ["Node Operation"]
    types:
      - completed
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
    infobae:
        name: Run K6 Local
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: grafana/setup-k6-action@v1
          - uses: grafana/run-k6-action@v1
            with:
              path: |
                performance/api-infobae.js
          