name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  telegram:
    name: Send Inline Telegram Message
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - uses: cbrgm/telegram-github-action@v1.0.9
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            🚀 **New commit by ${{ github.actor }}!**

            **Commit:** ${{ github.event.head_commit.message }}
            **Repository:** ${{ github.repository }}
            **View changes:** [GitHub Commit](${{ github.event.head_commit.url }})

            📎 **Commit Details:**
            - Author: ${{ github.event.head_commit.author.name }}
            - Email: ${{ github.event.head_commit.author.email }}
            - Date: ${{ github.event.head_commit.timestamp }}

            🌐 **Repository Details:**
            - Branch: ${{ github.ref }}
            - SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})