name: gitleaks

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  telegram:
    uses: jd-apprentice/jd-workflows/.github/workflows/telegram.yml@main
    with:
      message: |
            🚀 *New commit by ${{ github.actor }}!*

            *Commit:* ${{ github.event.head_commit.message }}
            *Repository:* ${{ github.repository }}
            *View changes:* [GitHub Commit](${{ github.event.head_commit.url }})

            📎 *Commit Details:*
            - Author: ${{ github.event.head_commit.author.name }}
            - Email: ${{ github.event.head_commit.author.email }}
            - Date: ${{ github.event.head_commit.timestamp }}

            🌐 *Repository Details:*
            - Branch: ${{ github.ref }}
            - SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
      runs-on: ubuntu-latest
      name: Telegram Notification
    secrets:
      envTOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      envCHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}