name: gitleaks

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  telegram:
    uses: jd-apprentice/jd-workflows/.github/workflows/telegram.yml@main
    with:
      message: |
        *Gitleaks Scan*
        *Repository:* ${{ github.repository }}
        *Branch:* ${{ github.ref }}
        *Event:* ${{ github.event_name }}
        *Commit:* ${{ github.sha }}
        
      runs-on: ubuntu-latest
      name: Telegram Notification
    secrets:
      envTO: ${{ secrets.TELEGRAM_TO }}
      envTOKEN: ${{ secrets.TELEGRAM_TOKEN }}
