name: gitleaks

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  telegram:
    name: Send Inline Telegram Message
    runs-on: ubuntu-latest
    needs: scan
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - uses: ./.github/workflows/telegram.yml
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}