name: Node03

on:
  workflow_dispatch:
  push:
    branches: [node03/*]
    paths:
      - "ansible/files/node03/**"
      - ".github/workflows/node03.yml"
      - "terraform/homelab/*"
  pull_request:
    branches: [node03/*]
    paths:
      - "ansible/files/node03/**"
      - ".github/workflows/node03.yml"
      - "terraform/homelab/*"

permissions:
  actions: write
  contents: write

env:
  NODE_NAME: node03

jobs:
  operation:
    uses: ./.github/workflows/node-operation.yml
    with:
      node-name: node03
      runs-on: self-hosted
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
