name: Node00

on:
  workflow_dispatch:
  push:
    branches: [node00/*]
    paths:
      - "ansible/files/node00/**"
      - ".github/workflows/node00.yml"
      - "terraform/homelab/*"
  pull_request:
    branches: [node00/*]
    paths:
      - "ansible/files/node00/**"
      - ".github/workflows/node00.yml"
      - "terraform/homelab/*"

permissions:
  actions: write
  contents: write

env:
  NODE_NAME: node00

jobs:
  operation:
    uses: ./.github/workflows/node-operation.yml
    with:
      node-name: $NODE_NAME
      runs-on: $NODE_NAME
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
