name: Node02

on:
  workflow_dispatch:
  push:
    branches: [node02/*]
    paths:
      - "ansible/files/node02/**"
      - ".github/workflows/node02.yml"
      - "terraform/homelab/*"
  pull_request:
    branches: [node02/*]
    paths:
      - "ansible/files/node02/**"
      - ".github/workflows/node02.yml"
      - "terraform/homelab/*"

permissions:
  actions: write
  contents: write

env:
  NODE_NAME: node02

jobs:
  operation:
    uses: ./.github/workflows/node-operation.yml
    with:
      node-name: node02
      runs-on: node02
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
