
name: Node04

on:
  workflow_dispatch:
  push:
    branches: [node04/*]
    paths:
      - "ansible/files/node04/**"
      - ".github/workflows/node04.yml"
      - "terraform/homelab/*"
  pull_request:
    branches: [node04/*]
    paths:
      - "ansible/files/node04/**"
      - ".github/workflows/node04.yml"
      - "terraform/homelab/*"

permissions:
  actions: write
  contents: write

env:
  NODE_NAME: node04

jobs:
  operation:
    uses: ./.github/workflows/node-operation.yml
    with:
      node-name: node04
      runs-on: node04
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
