name: Node03

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "ansible/files/node03/**"
      - ".github/workflows/node03.yml"

permissions:
  actions: write
  contents: write

env:
  NODE_NAME: node03

jobs:
  operation:
    if: github.repository == 'jd-apprentice/jd-server'
    uses: ./.github/workflows/node-operation.yml
    with:
      node-name: node03
      runs-on: node03
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
      user: ${{ secrets.USER }}
      cf_auth_client_id: ${{ secrets.CF_AUTH_CLIENT_ID }}
      cf_auth_client_secret: ${{ secrets.CF_AUTH_CLIENT_SECRET }}
      gotify_app_token: ${{ secrets.NODE_OPERATION_GOTIFY_TOKEN }}
