name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  TARGET: jonathan.com.ar

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ env.TARGET }}

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gotify:
    needs: [nuclei-scan]
    uses: ./.github/workflows/cloudflare-auth.yml
    secrets:
      cf_auth_client_id: ${{ secrets.CF_AUTH_CLIENT_ID }}
      cf_auth_client_secret: ${{ secrets.CF_AUTH_CLIENT_SECRET }}
      gotify_app_token: ${{ secrets.NUCLEI_GOTIFY_TOKEN }}
    with:
      runs-on: ubuntu-latest
      name: "Cloudflare Auth"
      gotify_server_url: "https://push.jonathan.com.ar"
      gotify_title: "Nuclei Security Scanner"
      gotify_description: "Security test passed"
      gotify_priority: 1
