apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dozzle
  name: dozzle
spec:
  ports:
    - name: "tcp"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: dozzle
