## Not used at the moment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dozzle
  name: dozzle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dozzle
  template:
    metadata:
      labels:
        io.kompose.service: dozzle
    spec:
      containers:
        - image: amir20/dozzle
          name: dozzle
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false